### ISSUE TITLE
What does `callm` mean?

### ISSUE THREAD

**Issue by EricLBuehler** [MistApproach/callm#1]
Hi @MistApproach !

Great work here, I'll definitely watch the progress! I was wondering, what does the name callm mean? Is it an amalgamation of candle and llm?

**Comment by MistApproach** [comment]
Thanks @EricLBuehler !

It's a pleasure to have you here! I have stumbled upon your projects in the past and i love them :)

As for the name, your guess is correct. Even though `callm` has LLM reference in its name, i plan to support other pipelines in the future (text-to-image, multi-modal). The way i think about the name is threefold:

* **ca**ndle **llm**
* the meaning of the word **calm**
* **call m**odels

Best regards!

**Comment by EricLBuehler** [comment]
That's great, thank you for the detailed explanation!
